# Site settings
title: Muhammad Iqbal Pamungkas - Blog
header-img: img/home-bg.jpg
email: iqbalpmgks@gmail.com
copyright_name: 2017. All right reserved.
description: "Starting from a sharing of experiences and knowledge!"
baseurl: ""
url: "https://iqbalpmgks.github.io"
twitter_username: iqbalpmgks
github_username:  iqbalpmgks
facebook_username:  iqbalpmgks
email_username:  iqbalpmgks@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
